// THE cross-boundary contract for the PayCross Flutter SDK.
//
// Regenerate with:
//   dart run pigeon --input pigeons/paycross_api.dart && dart format lib/src/generated
//
// The format step is not optional: Pigeon's Dart output is not
// `dart format`-clean, the committed copy is, and CI diffs the two.
//
// `pigeon` is pinned to an exact version (no caret) because both native sides
// must be generated by the same Pigeon. CI regenerates and fails on any diff.
//
// Generated output is NOT the public API. `lib/src/generated/` is deliberately
// not exported; the hand-written types in `lib/src/` are what merchants see.
// Pigeon's own docs discourage exposing generated code, and a merchant pinning
// this package has no resolver to protect them from a renamed field.
import 'package:pigeon/pigeon.dart';

@ConfigurePigeon(
  PigeonOptions(
    dartOut: 'lib/src/generated/paycross_api.g.dart',
    dartPackageName: 'paycross_flutter',
    kotlinOut:
        'android/src/main/kotlin/com/paycross/flutter/generated/PayCrossApi.g.kt',
    kotlinOptions: KotlinOptions(package: 'com.paycross.flutter.generated'),
    swiftOut: 'ios/Classes/generated/PayCrossApi.g.swift',
  ),
)
/// The backend the native SDK talks to.
///
/// Two cases only. iOS additionally has a `.custom(baseURL:)`; Android has no
/// equivalent, and its Retrofit client derives the base URL from the enum. A
/// `custom` case here would mean the same Dart call did different things on
/// each platform.
enum PcEnvironment { sandbox, production }

/// Prefills the native card form for manual test runs.
///
/// CARRIES A PAN AND A CVV, and is the only card data that ever crosses this
/// channel. It does so because the native form is one the plugin cannot reach
/// any other way. Both native SDKs already drop it outside sandbox; the Dart
/// facade throws if it is supplied with a production environment, and the
/// plugin drops it again before calling in.
///
/// Nothing about a real shopper's card crosses: CardData, CardFormState and
/// BrowserInfo are absent from this file by design.
class PcTestCardPrefill {
  PcTestCardPrefill({
    required this.cardholderName,
    required this.pan,
    required this.expireMonth,
    required this.expireYear,
    required this.cvv,
    required this.saveCard,
  });

  String cardholderName;
  String pan;

  /// "MM".
  String expireMonth;

  /// Four digits, e.g. "2028". Both native forms take the last two.
  String expireYear;

  String cvv;
  bool saveCard;
}

class PcConfiguration {
  PcConfiguration({
    required this.environment,
    this.brandColorArgb,
    this.testCardPrefill,
    this.googlePayMerchantId,
    this.applePayMerchantId,
  });

  PcEnvironment environment;

  /// Packed ARGB, sent unsigned. Kotlin receives Long? and calls toInt(), whose
  /// low-32-bit truncation is exactly the signed @ColorInt Android wants.
  ///
  /// Null means "platform default" and must stay a real null: 0x00000000 is
  /// transparent black, a legal colour rather than a sentinel.
  ///
  /// Android only in v1 — the iOS SDK has no brand-colour hook, and its only
  /// colour source is the host app's window tint, which the plugin must not set
  /// because tintColor inherits down the hierarchy and would repaint the
  /// merchant's entire app. iOS accepts and ignores this.
  int? brandColorArgb;

  PcTestCardPrefill? testCardPrefill;

  /// Google Business Console merchant id, for the Google Pay button the Android
  /// SDK renders itself when the session allows wallets.
  ///
  /// Google requires it in `merchantInfo` for PRODUCTION requests; the TEST
  /// environment works without one. Null is what "not configured" means: the
  /// native SDK adds `merchantId` to `merchantInfo` only when a non-blank id is
  /// present.
  ///
  /// Android only. Google Pay's in-app API is Android and web only, so there is
  /// no iOS wallet for this to configure and iOS accepts and ignores it.
  String? googlePayMerchantId;

  /// Apple Merchant ID, for the Apple Pay button the iOS SDK renders itself
  /// when the session allows wallets.
  ///
  /// Apple's key derivation hashes this string into every payment token's
  /// symmetric key, so it is not a display name and not optional decoration:
  /// the same value has to be registered with Apple, listed in the app's
  /// Apple Pay entitlement, and saved on the merchant's PayCross record. Null
  /// is what "not configured" means, and the iOS SDK renders no button for it.
  ///
  /// iOS only. Android has no Apple Pay, so it accepts and ignores this.
  String? applePayMerchantId;
}

class PcVersionInfo {
  PcVersionInfo({required this.pluginVersion, this.nativeSdkVersion});

  String pluginVersion;

  /// Nullable because the Android SDK exposes no version constant. The null
  /// makes that gap visible rather than inventing a string.
  String? nativeSdkVersion;
}

/// A monetary amount in minor units.
///
/// Pigeon `int` is Kotlin `Long` and Swift `Int64`. Never a double: a double
/// amount is the most expensive bug class in payments.
class PcAmount {
  PcAmount({required this.minorUnits, required this.currencyCode});

  int minorUnits;

  /// ISO 4217. May be the empty string when the session was already complete
  /// and the server returned no transaction reference.
  String currencyCode;
}

/// How a payment ended.
///
/// An empty sealed parent with concrete subclasses is the one inheritance shape
/// Pigeon supports, and only in the Kotlin, Swift and Dart generators — which
/// are exactly the three targets here. That is what lets the exhaustiveness the
/// native SDKs were built around survive the crossing.
sealed class PcPaymentResult {}

class PcSuccess extends PcPaymentResult {
  PcSuccess({
    required this.transactionId,
    required this.status,
    required this.amount,
  });

  /// Empty in the edge case where the session was already complete and the
  /// server returned no transaction reference. Not null — both native SDKs
  /// model this as a present-but-empty string.
  String transactionId;

  /// "success", "authorized", …
  String status;

  PcAmount amount;
}

class PcFailure extends PcPaymentResult {
  PcFailure({this.transactionId, required this.recovery});

  /// Null for failures that happen before a transaction exists.
  String? transactionId;

  /// The RAW server token, not a parsed enum.
  ///
  /// Pigeon cannot express an enum with an associated value, so a closed enum
  /// here would destroy any value the server adds later — exactly the case
  /// iOS's `.unrecognized(String)` exists to preserve. Dart re-parses this with
  /// the same rules both native SDKs use, so a new token degrades to
  /// "unrecognised, not retryable" instead of being silently rewritten.
  ///
  /// Empty string means the server sent nothing, which both SDKs read as retry.
  String recovery;
}

class PcCancelled extends PcPaymentResult {
  PcCancelled();
}

@HostApi()
abstract class PayCrossHostApi {
  /// Applies configuration to the native SDK.
  ///
  /// The plugin caches this and re-applies it lazily inside presentPayment.
  /// Without that, a hot restart or a second engine in an add-to-app host
  /// loses the Dart-side flag while the native process keeps running, and iOS
  /// hits assertionFailure — a hard trap in a debug build.
  void configure(PcConfiguration configuration);

  PcVersionInfo versionInfo();

  /// Presents the native payment UI, resolving when the payment reaches a
  /// terminal state or the shopper cancels.
  ///
  /// @async because this can take minutes: the poll deadline is 480s on both
  /// platforms. Callers must not wrap the returned Future in Future.timeout —
  /// a shorter timeout orphans a live payment while the native SDK keeps
  /// polling and may still charge the card.
  ///
  /// Declines are NOT errors; they arrive as PcFailure. An error from this
  /// method always means an integration mistake.
  @async
  PcPaymentResult presentPayment(String sessionToken);
}
